### ISSUE TITLE
Debugging issue

### ISSUE THREAD

**Issue by Subrina2020** [jlblancoc/suitesparse-metis-for-windows#100]
Tried to run the demo code inside the project. It doesn't start debugging process showing unable to start program .......(Debug path).....access denied.

**Comment by jlblancoc** [comment]
Hi, 

If you use Visual Studio, I think it might be that you just missed setting the project as "Active Target/Project"...

**Comment by Subrina-Shawlin** [comment]
Sorry for asking such novice question. I am new to Visual Studio and C. How to set the project as 'Active Target/Project'. To run a demo test, I have opened a new file inside the project (.sln file) and copied the demo code there. After hitting "Local Windows Debugger" buton, it shows the debugging error. I have tried running the project as startup project as well. Doesn't solve the problem. What is the correct way to run a sample code using SuiteSparse project. I feel like I am doing something wrong here.

**Comment by jlblancoc** [comment]
On Wed, Jul 8, 2020 at 4:53 PM Subrina-Shawlin <notifications@github.com> wrote:
> Sorry for asking such novice question. I am new to Visual Studio and C. How to set the project as 'Active Target/Project'. To run a demo test, I have opened a new file inside the project (.sln file) and copied the demo code there. After hitting "Local Windows Debugger" buton, it shows the debugging error. I have tried running the project as startup project as well. Doesn't solve the problem. What is the correct way to run a sample code using SuiteSparse project. I feel like I am doing something wrong here.

I hope you find this tutorial helpful (it's in Spanish, but you can
enable autotranslated English substitles):
https://www.youtube.com/watch?v=eNup_mFZxkU
