### ISSUE TITLE
multiple definition

### ISSUE THREAD

**Issue by boyob** [jlblancoc/suitesparse-metis-for-windows#104]
I had installed these. When I use these to compile G2O, I got into trouble:

D:/MinGW/libraries/lib/libcxsparse.a(cs_util_di.o.c.obj):cs_util_di.o.c:(.text+0x1e0): multiple definition of `cs_di_spfree'
../../../../bin/libg2o_csparse_extension.dll.a(d000026.o):(.text+0x0): first defined here
D:/MinGW/libraries/lib/libcxsparse.a(cs_util_di.o.c.obj):cs_util_di.o.c:(.text+0x220): multiple definition of `cs_di_nfree'
../../../../bin/libg2o_csparse_extension.dll.a(d000021.o):(.text+0x0): first defined here
D:/MinGW/libraries/lib/libcxsparse.a(cs_util_di.o.c.obj):cs_util_di.o.c:(.text+0x2b0): multiple definition of `cs_di_sfree'
../../../../bin/libg2o_csparse_extension.dll.a(d000024.o):(.text+0x0): first defined here
D:/MinGW/libraries/lib/libcxsparse.a(cs_malloc_di.o.c.obj):cs_malloc_di.o.c:(.text+0x0): multiple definition of `cs_di_malloc'
../../../../bin/libg2o_csparse_extension.dll.a(d000019.o):(.text+0x0): first defined here
D:/MinGW/libraries/lib/libcxsparse.a(cs_malloc_di.o.c.obj):cs_malloc_di.o.c:(.text+0x20): multiple definition of `cs_di_calloc'
../../../../bin/libg2o_csparse_extension.dll.a(d000007.o):(.text+0x0): first defined here
D:/MinGW/libraries/lib/libcxsparse.a(cs_malloc_di.o.c.obj):cs_malloc_di.o.c:(.text+0x40): multiple definition of `cs_di_free'
../../../../bin/libg2o_csparse_extension.dll.a(d000014.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status

Any help would be really appreciated.

**Comment by NeroBurner** [comment]
@jlblancoc I suggest closing this issue due to no response for a long time
