### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chenhonghua** [jlblancoc/suitesparse-metis-for-windows#12]
@jlblancoc 
Hi, jlblancoc,
I encountered some errors when I compile the example in SP_ROOT/example-projects/cholmod/ under Windows 64bits with VisualStdio 2013.
It shows that
error LNK2019: unresolved external symbol _cholmod_start, referenced in function _main
error LNK2019: unresolved external symbol _cholmod_finish, referenced in function _main
....etc.
Generally speaking, such errors mean that I haven't add the appropriate libs and include files. But in my project, I do add them. 
So, I am really confused about it.
Can you send me a off-the-shelf version?

**Comment by jlblancoc** [comment]
Make sure of being compiling both (the lib, and the example) in either
32 or 64bit! That is a common mistake we everyone do sometimes...


On Sun, Jun 14, 2015 at 3:15 PM, Chen Hong Hua <notifications@github.com> wrote:
> @jlblancoc
> Hi, jlblancoc,
> I encountered some errors when I compile the example in
> SP_ROOT/example-projects/cholmod/ under Windows 64bits with VisualStdio
> 2013.
> It shows that
> error LNK2019: unresolved external symbol _cholmod_start, referenced in
> function _main
> error LNK2019: unresolved external symbol _cholmod_finish, referenced in
> function _main
> ....etc.
> Generally speaking, such errors mean that I haven't add the appropriate libs
> and include files. But in my project, I do add them.
> So, I am really confused about it.
> Can you send me a off-the-shelf version?
>
> —
> Reply to this email directly or view it on GitHub.



-- 
___________________________________________________________

Dr. Jose-Luis Blanco-Claraco
CITE-IV 1.05
Universidad de Almería, Departamento de Ingeniería
04120 Almería (Spain)
http://www.ual.es/~jlblanco/
___________________________________________________________

**Comment by chenhonghua** [comment]
@jlblancoc 
Hi.
I am sure that i have compiled both (the lib, and the example). But the errors still exist!
Can you send me a already-compiled version(Win7 64bit VS2013)? Maybe we can see something different.

**Comment by chenhonghua** [comment]
@jlblancoc 
Follow your advice, all errors are gone! Thank you !

**Comment by fredlll** [comment]
@chenhonghua Can you share how you solved the problem? i face the same unresolved external symbol error. 

i did not get how to "compiling both (the lib, and the example)" as i did not see the example solution
