### ISSUE TITLE
No lapack_blas_windows folder found

### ISSUE THREAD

**Issue by Alexandre-Bonneau** [jlblancoc/suitesparse-metis-for-windows#121]
Hi, I'm installing suitesparse for windows, and when I'm looking for lapack_blas_windows in order to add it to my environment path, I can't find it.

It should be in CMAKE_INSTALL_PREFIX\lib*\lapack_blas_windows\, however, in CMAKE_INSTALL_PREFIX\lib there are only a debug and release folder.

**Comment by NeroBurner** [comment]
The prebuilt lapack libraries for windows can be found here https://github.com/jlblancoc/suitesparse-metis-for-windows/tree/master/lapack_windows

Alternatively you can build using OpenBLAS by configuring CMake with WITH_OPENBLAS=ON

Then you can have a static lib only build with no runtime libraries needed. All statically compiled

**Comment by NeroBurner** [comment]
closed due to inactivity
