### ISSUE TITLE
Error to build example project if enable BUILD_METIS

### ISSUE THREAD

**Issue by simbaforrest** [jlblancoc/suitesparse-metis-for-windows#14]
Hi Jose Luis Blanco,

First of all, thanks for creating this project!

When I build the project with BUILD_METIS on, everything builds fine. However if I build the example project "cholmod", a linking error shows "METIS_NodeComputeSeparator" cannot be found in any .lib file (I checked that all lib files were correctly linked). I believe this might be due to the reason that the METIS 5.1.0 do not have this function anymore. Maybe we should switch back to METIS 4?

Best,
Chen

**Comment by jlblancoc** [comment]
It should be fixed now with https://github.com/jlblancoc/suitesparse-metis-for-windows/commit/cf44ddae6a25371e622aa8b8a506d8527fb31266

**Comment by jlblancoc** [comment]
Nope, it should not be defined!! Look here (also I just checked preprocessor flags from MSVC and NPARTITION is not there): https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/SuiteSparse/CMakeLists.txt#L10

Ah, and thank @dtmoodie for the GPU work! ;-)

**Comment by simbaforrest** [comment]
But in [here](https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/UseSuiteSparseForInstall.cmake.in#L96) you add it...

**Comment by jlblancoc** [comment]
Absolutely true!! 

If you have any example code that fails due to this, please, try just moving that line 96 after the "else()" and test if that solves the problem. 

You could fork and apply the change there, so I could later do a pull request, ok? 

Thanks!

**Comment by simbaforrest** [comment]
Sure I will do that. But what about the other one?

https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/cmakemodule/FindSuiteSparse.cmake#L248

**Comment by jlblancoc** [comment]
Give it a try now, but I think it should do it...
