### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by magnese** [jlblancoc/suitesparse-metis-for-windows#15]
Hi,
what is the licence for the FindCMake scripts? 
Can this file be included into an open source project under the licence GPL2 with runtime exception?

Regards,
Marco.

**Comment by jlblancoc** [comment]
Hi Marco, 

We have updated the files to reflect the license: 3-clause BSD.

Cheers.

**Comment by magnese** [comment]
Thank you for the prompt update.

Cheers
