### ISSUE TITLE
SuiteSparse version 4.4.3 does not work with latest metis

### ISSUE THREAD

**Issue by spraetor** [jlblancoc/suitesparse-metis-for-windows#18]
When using the SUITESPARSE_DL_LAST flag to download the latest library versions, the metis lib seems to be updated but suitesparse is fixed to version 4.4.3.
This gives a problem when linking against cholmod, since cholmod of suitesparse 4.4.3 is not compatible with latest metis (the interface of metis changed slightly)

For the current suitesparse version 4.5.1 it is claimed that it works well with the current metis (and in my test there were no problems when linking). Thus, the fixed version should be corrected to 4.5.1 or at least a comment added in the cmake-file.

**Comment by jlblancoc** [comment]
Thanks! It should be fixed now with the latest commits and the new release. 

Closing.
