### ISSUE TITLE
Visual Studio 2015 Math.h Error

### ISSUE THREAD

**Issue by MikePelton** [jlblancoc/suitesparse-metis-for-windows#19]
In a throw back to  issue 6, Visual Studio 2015 _does_ define "rint" and "INFINITY", and so there's a syntax error reported in math.h - the fix from Issue 6 defines "rint" for _MSC_ compilers. (It's "rint" that's a problem; the redefinition of INFINITY just causes some warnings).

The fix is to test for a version before 1900 (which is VS2015) as below:
```
#ifdef __MSC__
/* MSC may not have rint() function */
#if(_MSC_VER < 1900)
#define rint(x) ((int)((x)+0.5))  
#endif

/* MSC does not have INFINITY defined */
#ifndef INFINITY
#if(_MSC_VER < 1900)
#define INFINITY FLT_MAX
#endif
#endif
#endif
```
I don't speak Git so if someone else could confirm I'm right and make the change that would save others from traversing this path!

**Comment by sluki** [comment]
Visual Studio 2013 Update 5 (maybe also earlier, I don't know) also has function 'rint'

problematic definition of 'rint' can be found in following files:
 - metis/programs/metisbin.h
 - GKlib/gk_arch.h
 - libmetis/metislib.h
