### ISSUE TITLE
SuiteSparse_FOUND heads up for Ceres

### ISSUE THREAD

**Issue by MikePelton** [jlblancoc/suitesparse-metis-for-windows#20]
**_IF_** you're following this route to try and get Ceres built under VS2013, if you follow the instructions here and drop the suggested (and included here)  FindSuiteSparse.cmake file into the ceres-solver-1.11.0/cmake folder you'll find that, despite everything being located, Ceres' cmake still thinks finding SuiteSparse has failed. This is easily resolved! CMake variables are case-sensitive - the variable that gets set here is SuiteSparse_FOUND, but the one Ceres' CMakeLists.txt is looking for is SUITESPARSE_FOUND. Change one or the other and all will be well.

**Comment by jlblancoc** [comment]
Hi @MikePelton , and thanks for the feedback!

I guess `SUITESPARSE_FOUND` is set by other `FindSuiteSparse.cmake` scripts which usually locate the lib in Linux systems, so I'm not 100% sure the rest of output variables will be compatible such that Ceres ends up building clean... have you verified it? 

If yes, one "ugly" but efficient solution would be to set both `SUITESPARSE_FOUND` and `SuiteSparse_FOUND` in `FindSuiteSparse.cmake`, ok?

**Comment by MikePelton** [comment]
Hi @jlblancoc and many thanks for coming back so quickly. Interestingly having looked at the issue here, my Visual Studio build of Ceres doesn't see the includes and libs for SuiteSparse, so there are probably other variables the Ceres guys are expecting to see exported. I'm not sure how we'd address that - your code can't anticipate what other people will do! I'll be looking more at the Ceres side soon so will raise it with them. Your work here is a life saver, so many thanks indeed!

**Comment by jlblancoc** [comment]
@MikePelton You're welcome! Feel free to propose any changes in our `FindSuiteSparse.cmake` that makes it more compatible with Ceres.
