### ISSUE TITLE
Error on vs2015

### ISSUE THREAD

**Issue by tmac1002** [jlblancoc/suitesparse-metis-for-windows#21]
Hi, @jlblancoc when I followed by these steps, and then there are 7 errors all  about D8012. Can you please help me to look at it?
![default](https://cloud.githubusercontent.com/assets/11924213/14919657/6228be64-0e5c-11e6-9a92-9e5c58c8c9d6.PNG)

**Comment by jlblancoc** [comment]
As per [this line](https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/be47632412f1fb182137f6f6eee31ae0816da8da/metis/GKlib/GKlibSystem.cmake#L54)
... have you checked an option called `GDB`  in CMake? If yes, please uncheck it since it's intended for Linux only...
