### ISSUE TITLE
Problem of build on VS 2013

### ISSUE THREAD

**Issue by xialang2012** [jlblancoc/suitesparse-metis-for-windows#23]
I downloaded suitesparse from https://github.com/jlblancoc/suitesparse-metis-for-windows/archive/v1.3.1.zip, then unpacked it, and under the instructions to build it.
But I have some errors to complete the build process, as shown beolow:

> ========== Build: 14 succeeded, 7 failed, 0 up-to-date, 1 skipped ========== 

some of the detailed errors
> Error	2	error C2059: syntax error : '('	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h	515	1	metis
> Error	348	error C2059: syntax error : '('	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h	515	1	metis
> Error	367	error C2059: syntax error : '('	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h	515	1	metis
>....

I do not know what's wrong about it.

**Comment by corfox** [comment]
[Visual Studio 2015 Math.h Error #19](https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/19)

metis/GKlib/gk_arch.h
`
#ifdef __MSC__
/* MSC does not have rint() function */
#if (_MSC_VER < 1800)
 #define rint(x) ((int)((x)+0.5))  
#endif

/* MSC does not have INFINITY defined */
#ifndef INFINITY
#define INFINITY FLT_MAX
#endif
#endif
`
