### ISSUE TITLE
How to use  CHOLMOD (such as Cholesky factorization) to solve  Ax = b if A is non symmetric?

### ISSUE THREAD

**Issue by wguo68** [jlblancoc/suitesparse-metis-for-windows#25]
Do the equation should be converted A^t _A = A^t_b? Then A^t _A as the sparse symmetric positive definite matrices? Is there any function to do the multiplication of  large sparse matrix A^t_A and A^t *b?

Thanks

**Comment by gzgius** [comment]
Use Umfpack for unsymmetric system instead.
GZ
Il 16/lug/2016 09:42, "wguo68" <notifications@github.com> ha scritto:
