### ISSUE TITLE
Input Error: Incorrect objective type when use cholmod?

### ISSUE THREAD

**Issue by hwdong** [jlblancoc/suitesparse-metis-for-windows#26]
When I use cholmod,  there is "Input Error: Incorrect objective type when use cholmod" In following code lines of "option.c" :

 case METIS_OP_OMETIS:
      if (ctrl->objtype != METIS_OBJTYPE_NODE) {
        IFSET(dbglvl, METIS_DBG_INFO, printf("Input Error: Incorrect objective type.\n"));
        return 0;
      }

What's the problem?

Thanks

**Comment by NeroBurner** [comment]
I think you used metis wrong (supplied the wrong parameter) and the checks tell you that something is wrong. If this still is a problem please report upstream

@jlblancoc I don't think this is a problem with the cmake packaging of this project. Please close
