### ISSUE TITLE
mUMFPACK module Fortran

### ISSUE THREAD

**Issue by FelipeAAlves** [jlblancoc/suitesparse-metis-for-windows#27]
Hi, 

I am new to VS and Fortran and I would appreciate if you could help me...

I followed all the steps and was able to build the INSTALL project on VS15. 
Now, what I would like is to use the mUMFPACK module for Fortran.  What I did was
1. On the build/SuiteSparse/SuiteSparse.sln I added a project MAIN with 2 files: main.f90 which calls the module umfpack.f90 and the module itself. 
2. On the umfpack.f90 file I add the command _INCLUDE 'umfpack.h'_. 
3. Right-click the executable Fortran MAIN project and select Dependencies to set the executable project as dependent on the umfpack project

When I try to build it, though, I get the following error. Are the steps correct? What am I missing?

Compiling with Intel(R) Visual Fortran Compiler 17.0.0.109 [IA-32]...
ifort /nologo /debug:full /Od /warn:interfaces /module:"Debug\" /object:"Debug\" /Fd"Debug\vc140.pdb" /traceback /check:bounds /check:stack /libs:dll /threads /dbglibs /c /Qlocation,link,"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin" /Qm32 "C:\Users\falves\Dropbox\Repo\hank-main\umfpack.f90"
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(1): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/\* ========================================================================== _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(2): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ === umfpack.h ============================================================ _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(3): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ ========================================================================== _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(5): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ -------------------------------------------------------------------------- _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(6): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ Copyright (c) 2005-2012 by Timothy A. Davis, http://www.suitesparse.com.   _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(7): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ All Rights Reserved.  See ../Doc/License for License.                      _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(7): error #5082: Syntax error, found IDENTIFIER 'RESERVED' when expecting one of: => = / , [ ( \* <END-OF-STATEMENT> ;
/_ All Rights Reserved.  See ../Doc/License for License.                      _/
--------------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(7): error #5082: Syntax error, found '.' when expecting one of: [ <IDENTIFIER>
/_ All Rights Reserved.  See ../Doc/License for License.                      _/
------------------------------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(8): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ -------------------------------------------------------------------------- _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(10): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(11): error #5082: Syntax error, found IDENTIFIER 'IS' when expecting one of: => = . [ % ( :
    This is the umfpack.h include file, and should be included in all user code
---------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(12): error #5082: Syntax error, found IDENTIFIER 'USES' when expecting one of: => = . [ % ( :
    that uses UMFPACK.  Do not include any of the umf_\* header files in user
---------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(12): error #5082: Syntax error, found IDENTIFIER 'NOT' when expecting one of: .EQV. .NEQV. .XOR. .OR. .AND. .LT. < .LE. <= .EQ. == .NE. /= .GT. > ...
    that uses UMFPACK.  Do not include any of the umf_\* header files in user
---------------------------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(13): error #5144: Invalid character_kind_parameter. No underscore
    code.  All routines in UMFPACK starting with "umfpack_" are user-callable.
-----------------------------------------------------------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(13): error #5082: Syntax error, found IDENTIFIER 'ROUTINES' when expecting one of: => = / . , [ % ( <END-OF-STATEMENT> ; : )
    code.  All routines in UMFPACK starting with "umfpack_" are user-callable.
---------------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(14): error #5144: Invalid character_kind_parameter. No underscore
    All other routines are prefixed "umf_XY_", (where X is d or z, and Y is
---------------------------------------------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(14): error #5082: Syntax error, found 'ALL' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
    All other routines are prefixed "umf_XY_", (where X is d or z, and Y is
----^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(15): error #5276: Unbalanced parentheses
    i or l) and are not user-callable.
----------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(15): error #5082: Syntax error, found IDENTIFIER 'OR' when expecting one of: => = . [ % ( :
    i or l) and are not user-callable.
------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(18): warning #5117: Bad # preprocessor line
# ifndef UMFPACK_H

-^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(19): warning #5117: Bad # preprocessor line
# define UMFPACK_H

-^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(16): error #5082: Syntax error, found '_' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
*/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(21): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ -------------------------------------------------------------------------- _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(22): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ Make it easy for C++ programs to include UMFPACK _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(22): error #5082: Syntax error, found IDENTIFIER 'EASY' when expecting one of: => = / , [ ( \* <END-OF-STATEMENT> ;
/_ Make it easy for C++ programs to include UMFPACK */
-----------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(25): warning #5117: Bad # preprocessor line
# ifdef __cplusplus

-^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(23): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/\* -------------------------------------------------------------------------- */
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(26): error #5144: Invalid character_kind_parameter. No underscore
extern "C" {
----------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(27): warning #5117: Bad # preprocessor line
# endif

-^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(29): warning #5117: Bad # preprocessor line
# include "SuiteSparse_config.h"

-^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(26): error #5078: Unrecognized token '{' skipped
extern "C" {
-----------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(26): error #5082: Syntax error, found CHARACTER_CONSTANT 'C' when expecting one of: => = . [ % ( :
extern "C" {
-------^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(31): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/\* -------------------------------------------------------------------------- _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(32): error #5082: Syntax error, found '/' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
/_ size of Info and Control arrays _/
^
C:\SP_ROOT\build\install\include\suitesparse\umfpack.h(32): error #5082: Syntax error, found IDENTIFIER 'INFO' when expecting one of: => = / , [ ( \* <END-OF-STATEMENT> ;
/_ size of Info and Control arrays */
-----------^
C:\Users\falves\Dropbox\Repo\hank-main\umfpack.f90(46): catastrophic error: Too many errors, exiting
compilation aborted for C:\Users\falves\Dropbox\Repo\hank-main\umfpack.f90 (code 1)

ifort /nologo /debug:full /Od /warn:interfaces /module:"Debug\" /object:"Debug\" /Fd"Debug\vc140.pdb" /traceback /check:bounds /check:stack /libs:dll /threads /dbglibs /c /Qlocation,link,"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin" /Qm32 "C:\Users\falves\Documents\Visual Studio 2015\Projects\SuiteSparse_test\main.f90"

**Comment by NeroBurner** [comment]
as far as I've found through a fast search is that fortran does not process the `#define` and other c-statements well. So no luck trying to use these c/c++ headers in fortran

https://stackoverflow.com/questions/14629307/including-a-c-c-header-file-in-fortran-subroutines

@jlblancoc please close
