### ISSUE TITLE
how to generate dll's for suitesparse

### ISSUE THREAD

**Issue by KlausBlass** [jlblancoc/suitesparse-metis-for-windows#29]
I just built SuiteSparseProject according to your instructions and built the INSTALL project in VS2015.
What I need now is a dll for umfpack. Should this already have been generated? (No dll's have been generated in either the SP_Root or build dirs).
Or which steps will generate it? Thanks.

**Comment by jlblancoc** [comment]
Hi,

Generating DLLs is not supported by the upstream project, sorry...

**Comment by jlblancoc** [comment]
Update from the future! CMake >=3.4 has an option that allows DLLs to finally be generated even for projects with source code not prepared to that.

It's in "beta", but should work after the recent commit referenced above.
