### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by VVE** [jlblancoc/suitesparse-metis-for-windows#30]
Hi,
Compiling this project in Visual Studio 2015, I got an error message:
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\math.h(520): error C2059: syntax error: (
In math.h(520) I see: 
_Check_return_ _ACRTIMP double __cdecl rint(_In_ double _X);
What should I fix? I try to use suitesparse-metis-for-windows for ceres-solver

**Comment by jlevallois** [comment]
Hi @VVE,

Check this issue: https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/23

A short fix is to add a check of the Visual Studio version in metis\GKlib\gk_arch.h:

```c++
#ifdef __MSC__
#if (_MSC_VER < 1800)
/* MSC does not have rint() function */
#define rint(x) ((int)((x)+0.5))
#endif
//....
```

`rint()` is available from Visual Studio 2013 (`_MSC_VER` 1800)

:octocat:

**Comment by Lokeshmsit** [comment]
Thanks, i rather commented the #define rint(x) ((int)((x)+0.5)) in maths.h.

**Comment by zbeekman** [comment]
good lord, why is metis' build system so janky... I'm hoping that this is the only magic I need to get over this hurdle for a METIS build myself... Thanks for providing this fix.
