### ISSUE TITLE
Why is the function 'cholmod_start' only declared but undefined? 

### ISSUE THREAD

**Issue by hyhrob** [jlblancoc/suitesparse-metis-for-windows#31]
In file 'suitesparse-metis-for-windows\SuiteSparse\CHOLMOD\Include\cholmod_core.h', line 1058:
```
int cholmod_start
(
    cholmod_common *Common
) ;
```
It is only declared but no function defined. Can anyone tell me why?

**Comment by jlblancoc** [comment]
Hi, 

It seems it was a bug in the original suitesparse package upstream... Some quick googling gave me: 
- http://octave.1599824.n4.nabble.com/quot-checking-for-cholmod-start-in-lcholmod-no-quot-td4663980.html
- https://bugs.launchpad.net/dorsal/+bug/1163822
