### ISSUE TITLE
\cholmod\supernodal\../GPU/t_cholmod_gpu.c(118): error C2036: 'void *': unknown size and error C2065: '__compar_fn_t': undeclared identifier

### ISSUE THREAD

**Issue by wguo68** [jlblancoc/suitesparse-metis-for-windows#33]
\cholmod\supernodal\../GPU/t_cholmod_gpu.c(118): error C2036: 'void *': unknown size
error C2065: '__compar_fn_t': undeclared identifier

When I build suitesparse windows using vs2015 and CUDA8

**Comment by oracle3001** [comment]
I am experiencing the same issue with VS2015 and CUDA 8.0. I have also tried upgrading the SpareSuite source to 4.5.5, and similarly all errors are CUDA related.

**Comment by ddmmccd** [comment]
gpu_p->d_Lx[0] = (cholmod_gpu_pointers *)Common->dev_mempool;
	gpu_p->d_Lx[1] = (cholmod_gpu_pointers *)Common->dev_mempool + Common->devBuffSize;
	gpu_p->d_C = (cholmod_gpu_pointers *)Common->dev_mempool + 2 * Common->devBuffSize;
	gpu_p->d_A[0] = (cholmod_gpu_pointers *)Common->dev_mempool + 3 * Common->devBuffSize;
	gpu_p->d_A[1] = (cholmod_gpu_pointers *)Common->dev_mempool + 4 * Common->devBuffSize;
	gpu_p->d_Ls = (cholmod_gpu_pointers *)Common->dev_mempool + 5 * Common->devBuffSize;
	gpu_p->d_Map = (cholmod_gpu_pointers *)gpu_p->d_Ls + (nls + 1)*sizeof(Int);
	gpu_p->d_RelativeMap = (cholmod_gpu_pointers *)gpu_p->d_Map + (n + 1)*sizeof(Int);

From：
https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/17
https://social.msdn.microsoft.com/Forums/en-US/043c1583-cbf3-4402-93c2-efc55cd70892/error-c2036-void-unknown-size?forum=vcgeneral

**Comment by ddmmccd** [comment]
For C2065：

typedef int(*__compar_fn_t)(const void*, const void*);

**Comment by JunhyeopLee** [comment]
Try this

typedef int (*__compar_fn_t) (const void *, const void *);
