### ISSUE TITLE
Error running cholmod_demo.c

### ISSUE THREAD

**Issue by elia-maracani** [jlblancoc/suitesparse-metis-for-windows#34]
Hi, I'm trying to use your library and was testing the cholmod_demo.c but we ran into an issue. 
When trying to compile the file in VS, the IDE signaled 
`Bx = B->x;` **Impossible to assign a type void * to a type double*. **

Any idea why?

P.S. We did import all the headers and libs as in your example, the IDE finds all the references, so that's not the problem I think.

Thanks.

**Comment by jlblancoc** [comment]
Hi,

Did this happen **after** successfully building the library?

Did you use CMake to setup the example or a manually-created project?

What version of VS do you use?

Make sure the source file has, inside the the "properties" panel, "compile
as C" instead of C++...

Cheers

**Comment by elia-maracani** [comment]
Hi, looks like my friend, who ran into this issue didn't build succesfully the lib. I'm sorry to have bothered you with this :/

I did manage to compile the lib, link and run a program using it, so now everything is fine! Thanks ;)

**Comment by jlblancoc** [comment]
No problem! 👍
