### ISSUE TITLE
SuiteSparseConfig.cmake doesn't work well with user define LIB_POSTFIX

### ISSUE THREAD

**Issue by KindDragon** [jlblancoc/suitesparse-metis-for-windows#35]
I configure my SuiteSparse with `-DLIB_POSTFIX=`, but `SuiteSparseConfig.cmake` still trying to use UseSuiteSparse64.cmake that doesn't exist

**Comment by NeroBurner** [comment]
Is this still an issue? Since July 5th we let the installed config be generated by cmake and there is no `UseSuiteSparse64.cmake` file anymore

**Comment by KindDragon** [comment]
No, thank you
