### ISSUE TITLE
Is SuiteSparse 64 bit compatible?

### ISSUE THREAD

**Issue by elia-maracani** [jlblancoc/suitesparse-metis-for-windows#37]
Hi, I managed to make a program that works using CSparse lib. It works as long as I tell VS to compile it as 32 bit, but since the matrices I'll have to work with in the final version are WAY bigger, I'll need to use a 64 bit version. Here comes the problem.
When I tell VS to compile as 64 bit, it gives me these 2 errors:
`1>matrix-math.obj : error LNK2001: external symbol cs_lsolve unresolved`
`1>matrix-math.obj : error LNK2001: external symbol cs_load unresolved`

Is SuiteSparse 64 bit compatible? If so, is there a way to "make it" 64 bit?

**Comment by jlblancoc** [comment]
Hi Elia,

It sounds like your user project is 64b, but its cmake suitesparse dir is pointing to a 32b build... please check it...

**Comment by elia-maracani** [comment]
I'm sorry, I don't understand, what do you mean by "its cmake suitesparse dir is pointing to a 32b build"? When I used to CMake to "make" the SuiteSparse dir there was no option to choose whether 32b or 64b.

Am I missing something? :/

**Comment by jlblancoc** [comment]
Click delete cache in cmake, configure again, there you'll be able to select visual studio 64b

**Comment by elia-maracani** [comment]
Once again, I feel dumb. It works now. Thanks :)
