### ISSUE TITLE
To build CHOLMOD 3.0.0 using CMake

### ISSUE THREAD

**Issue by KaiwenGuo** [jlblancoc/suitesparse-metis-for-windows#4]
Hi,
My name is Kevin. Thanks for CMake version. I notice that your CMake version does not involve GPU module in lastest CHOLMOD release.

 In lastest CHOLMOD release, four files are added to $(CHOLMOD)\GPU\, a cuda source file "cholmod_gpu_kernels.cu", a c source file, "cholmod_gpu.c", a dummy file "cholmod_gpu_kernels.c", and a template file "t_cholmod_gpu.c".

 I follow your style, adding "cholmod_gpu.o.c" and "cholmod_l_gpu.o.c" to "SourceWrappers" folder, and expand contents in each source wrapper. I build "cholmod_gpu_kernels.cu" in a separate visual studio project, generating "cholmod_gpu_kernels.lib" static library. Then I link this library to cmake-generated cholmod project. I add "GPU_BLAS" to preprocessor. 

There are some problems in Tim's source code of "t_cholmod_gpu.c". In line 94, "feenableexcept()" function is referenced from header "fenv.h", but that function is not available in visual studio. In line 117 - 124, pointers "Common->dev_mempool", "gpu_p->d_Ls", and "gpu_p->d_Map" are the type of "void*", they have to be converted to "unsigned char*" before shifted by offset. In line 274, compare function "__compar_fn_t" is not declared. I declared it by "typedef int (* __compar_fn_t) (const void*, const void*)".

 After these modification, I build cholmod project. generating "libcholmod.lib". Then I try demo "cholmod_l_demo.c". I comment "cholmod_l_version()" function in line 135, since that is a dummy function, and add "cm->useGPU=1" right under line 101 "cholmod_l_start(cm);".I add "GPU_BLAS" to preprocessor, then link demo project  to "cudart_static.lib", "cublas.lib", and "cholmod_gpu_kernels.lib", "liblapack.lib", "libblas.lib". Then I build this project and run it. But from printed results, gpu functions are not called.

 Can you give a try to this new version of CHOLMOD? Thank you!

**Comment by jlblancoc** [comment]
I think this should be fixed with the latest release, let us know if it is not...

**Comment by letienhung** [comment]
I think these issues are not fixed yet in 1.3.0

**Comment by myanuka** [comment]
Hi
I am using version 1.3.1 to build the cholmode GPU environment, however ,as mentioned, there is no implementation of cholmode_l_solve() functions. Even-though the GPU libraries are generated.
From the discussion I understand that some modifications has to be made.
Do you have a package that includes these modifications?
