### ISSUE TITLE
A problem when build suitesparse-metis-for-windows with CUDA 

### ISSUE THREAD

**Issue by lujun2445** [jlblancoc/suitesparse-metis-for-windows#45]
Hi everyone, I use CMake to generate .sln file, I use visual studio 2015, 64 bit machine, when I do not select  WITH_CUDA in configure, the generate sln file can build successfully, it works all OK, but when I select WITH_CUDA, and these are some of the settings in CMake:
CUDA_HOST_COMPILER: $(VCInstallDir)bin
CUDA_SDK_ROOT_DIR: CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_TOOLKIT_ROOT_DIR: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
CUDA_USE_STATIC_CUDA_RUNTIME: YES
I have installed CUDA 8.0 and test CUDA successfully. When I build the SuiteSparseProject.sln, some of errors have occurred:
Error	C2821; first formal parameter to 'operator new' must be 'size_t'; GPUQREngine; d:\project\suitesparse\suitesparse-metis-for-windows\suitesparse\gpuqrengine\include\GPUQREngine_Front.hpp,	Line50	
the code is:
void* operator new(long unsigned int reqMem, Front* ptr){ return ptr; }
how can I fix it? thanks very much!

**Comment by oracle3001** [comment]
replace the "long unsigned int" type with size_t

**Comment by jlblancoc** [comment]
Fixed by #68
