### ISSUE TITLE
error C2059: syntax error:“(”    for VS2013

### ISSUE THREAD

**Issue by cheneyfan** [jlblancoc/suitesparse-metis-for-windows#47]

**Comment by jlblancoc** [comment]
Where does it happen?  File and line number?

**Comment by portos53** [comment]
Issue fixed on StackOverflow:
https://stackoverflow.com/questions/35562135/rint-issue-after-creating-vs-project-using-cmake

"go to : metis\GKlib\gk_arch.h and metisbin.h and metislib.h. Remove or rename #define rint(x) ((idx_t)((x)+0.5)) it's causing a conflict with the rint function in math.h."

**Comment by jlblancoc** [comment]
@portos53 Thanks! 

Let me know if the less drastic change in a40e3f5244a25eadcdf0c5e5a99531f594e88661 also works for you. In this way, code will keep building for older MSVC versions.

**Comment by portos53** [comment]
Your less drastic change worked but you forget to add it in the file metis\GKlib\gk_arch.h. Once done, the build works.

**Comment by ComFreek** [comment]
It seems that these fixes have been overwritten due to a Suitesparse update, e.g. see [gk.arch.h#L63](https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/metis/GKlib/gk_arch.h#L63).
