### ISSUE TITLE
looking for latest cmake to suiteSparse for windows

### ISSUE THREAD

**Issue by myanuka** [jlblancoc/suitesparse-metis-for-windows#48]
Hi
I am using version 1.3.1 to build the cholmode GPU environment, however ,as mentioned, there is no implementation of  cholmode_l_solve() functions. Even-though the GPU libraries are generated.
From the discussion I understand that some modifications has to be made.
Do you have a package that includes these modifications?

**Comment by jlblancoc** [comment]
Should be fixed with the latest release (v1.4.0 as of today).
