### ISSUE TITLE
 Unknown CMake command "install_suitesparse_project".

### ISSUE THREAD

**Issue by 960956278** [jlblancoc/suitesparse-metis-for-windows#58]
Please help me(following is the codes in CMakeLists.txt)
PROJECT(suitesparseconfig)

include_directories("${suitesparseconfig_SOURCE_DIR}")

ADD_LIBRARY(suitesparseconfig STATIC
	SuiteSparse_config.c
	SuiteSparse_config.h
	)

install_suitesparse_project(suitesparseconfig "SuiteSparse_config.h")

**Comment by jtrautmann** [comment]
I also got this error. It was my mistake: I tried to run cmake in the SuiteSparse subdirectory. When I ran cmake in the top-level directory, this error disappeared.

**Comment by jlblancoc** [comment]
>  It was my mistake: I tried to run cmake in the SuiteSparse subdirectory.

Thanks!
