### ISSUE TITLE
Errors with Metis

### ISSUE THREAD

**Issue by letienhung** [jlblancoc/suitesparse-metis-for-windows#6]
I tried to compile SuiteSparse+Metis again and got a bunch of new errors (I've never seen them before)

error C2059: syntax error : '(' C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h 515

I spent hours to find out how to fix them: need to remove from "metis/GKlib/gk_arch.h" 

				#ifdef __MSC__ 
				/* MSC does not have rint() function */ 
				#define rint(x) ((int)((x)+0.5)) 

				/* MSC does not have INFINITY defined */ 
				#ifndef INFINITY 
				#define INFINITY FLT_MAX 
				#endif 
				#endif 

I know these errors come from Metis, should we put a small notice of them in the front page?

**Comment by rishabh-battulwar** [comment]
The errors on math.h are an issue, and the above solution solves it. But I'm still getting errors for cholmod_metis.c

Multiple errors of the following kind:

Error	589	error C2065: 'idxtype' : undeclared identifier ..\SP_ROOT\SuiteSparse\CHOLMOD\Partition\cholmod_metis.c	164

**Comment by jlblancoc** [comment]
@rishabh-battulwar  Those errors were detected time ago in SuiteSparse, here you have a patch for it: 
http://www.cise.ufl.edu/research/sparse/cholmod/metis.patch

Basically: replace `idxtype` ==> `idx_t`

I'm closing this bug since it's actually related to 3rd party libs.
