### ISSUE TITLE
Changing the option `SUITESPARSE_INSTALL_PREFIX` has no effect when using `cmake-gui`

### ISSUE THREAD

**Issue by romanc** [jlblancoc/suitesparse-metis-for-windows#62]
I'd like to install suitesparse into a custom location. This is supported with `SUITESPARSE_INSTALL_PREFIX`. While setting `SUITESPARSE_INSTALL_PREFIX` from the command line probably works, it's not possible to change the installation prefix when using CMake gui. The problem is the following. To be able to see (and therefore change) the option `SUITESPARSE_INSTALL_PREFIX`, you need to configure once. Configuring the first time will set `CMAKE_INSTALL_PREFIX` to the default value for `SUITESPARSE_INSTALL_PREFIX`. Now, if you go and change `SUITESPARSE_INSTALL_PREFIX` this change will not be propagated to `CMAKE_INSTALL_PREFIX` because `CMAKE_INSTALL_PREFIX` is already initialized to a non-default value, therefore the `if` clause [1] is false and `CMAKE_INSTALL_PREFIX` is not updated as proposed.

A fix would probably look something like

```
IF(WIN32 AND (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT OR CMAKE_INSTALL_PREFIX != SUITESPARSE_INSTALL_PREFIX))
```
where I'm usure about how to compare the value of two variables in CMake.

[1] https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/CMakeLists.txt#L18

**Comment by jlblancoc** [comment]
Should be fixed after d5c1cf2040e3e34434c59bde84700c3ffec2035f

Cheers!
