### ISSUE TITLE
Cannot find source file: GKlib/conf/check_thread_storage.c

### ISSUE THREAD

**Issue by jtrautmann** [jlblancoc/suitesparse-metis-for-windows#66]
From the README:

> Apparently only for Linux: if you have an error like: "Cannot find source file: GKlib/conf/check_thread_storage.c", then manually adjust GKLIB_PATH to the correct path SP_ROOT/metis/GKlib.

I also got this error on Windows. Manually adjusting GKLIB_PATH solved it. Maybe you could change this part in the README, as I didn't read it becaus of the "only for Linux" part and so it took some time to find the error.

**Comment by jlblancoc** [comment]
👍 thanks!
