### ISSUE TITLE
rint is a c++11 feature

### ISSUE THREAD

**Issue by NeroBurner** [jlblancoc/suitesparse-metis-for-windows#71]
the current release (v1.4.0) does not compile under Ubuntu 18.04 with default configurations

```
Scanning dependencies of target metis
[  1%] Building C object metis/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o
In file included from /home/gc/repos/external/suitesparse-metis-for-windows/metis/GKlib/GKlib.h:23:0,
                 from /home/gc/repos/external/suitesparse-metis-for-windows/metis/GKlib/b64.c:20:
/home/gc/repos/external/suitesparse-metis-for-windows/metis/GKlib/gk_arch.h:62:19: error: expected identifier or '(' before 'int'
 #define rint(x) ((int)((x)+0.5))
                   ^
/home/gc/repos/external/suitesparse-metis-for-windows/metis/GKlib/gk_arch.h:62:23: error: expected ')' before '(' token
 #define rint(x) ((int)((x)+0.5))
                       ^
metis/libmetis/CMakeFiles/metis.dir/build.make:62: recipe for target 'metis/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o' failed
make[2]: *** [metis/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o] Error 1
CMakeFiles/Makefile2:132: recipe for target 'metis/libmetis/CMakeFiles/metis.dir/all' failed
make[1]: *** [metis/libmetis/CMakeFiles/metis.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

it seems that the cmake check symbol does not find the `rint` function in `math.h` when no C++ standard is specified.

When I compile with `-DCMAKE_CXX_STANDARD=11` the build works as expected because `rint` is defined
http://www.cplusplus.com/reference/cmath/rint/

Can we require C++11 as default standard level? I would open a PR with the following behavior:
- if no standard is set, then use C++11
- if a standard is set then use the set standard

**Comment by jlblancoc** [comment]
Good point. I guess you refer to using the library via find_package()? In that case, it may be useful to set the cmake c++ standard, so yes please, go on with the pr.
