### ISSUE TITLE
FindSuiteSparse.cmake is not needed anymore

### ISSUE THREAD

**Issue by NeroBurner** [jlblancoc/suitesparse-metis-for-windows#80]
The find module is not needed anymore. CMake generates the suitesparse-config.cmake which can be used.

If it is not installed as system library the user can add the `-Dsuitesparse_DIR=/path/to/suitesparse-config.cmake` parameter to cmake config

I think we should remove https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/cmakemodule/FindSuiteSparse.cmake
and update the README.md appropriately

**Comment by jlblancoc** [comment]
Closed after #89
