### ISSUE TITLE
Broken CMakeList on Linux

### ISSUE THREAD

**Issue by jcouet** [jlblancoc/suitesparse-metis-for-windows#84]
There are two typos in two CMakeLists that break the build on linux system.

1.  https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/CMakeLists.txt#L213
`FIND_PACKAGE(cuda) -> FIND_PACKAGE(CUDA)`
The lowercase 'cuda' is not recognized on linux which is case sensitive

2. https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/SuiteSparse/GPUQREngine/CMakeLists.txt#L9
`CUDA_ADD_LIBRARY(GPUQREngine STATIC ${LIBHDRS} ${LIBSRCS})`
Forcing a static GPUQR compilation prevent the building a suite-sparse as a shared lib.
This Flag should be removed since the type of the build can be globally managed by the `BUILD_SHARED_LIBS`, see https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html

**Comment by jlblancoc** [comment]
Thanks! I don't have a CUDA dev environment setup nearby... could you please test the proposed changes and open a pull-request from your fork? The changes seem quite trivial, but I would prefer to make them from a **tested** fork.

**Comment by jcouet** [comment]
Hello Jose. Thank you very much.
I didn't know if was possible to create a PR from a fork, that's really nice.
I will wrap the PR very soon.

**Comment by NeroBurner** [comment]
closed due to inactivity
