### ISSUE TITLE
CMake Error: include called with wrong number of arguments.  include() only takes one file

### ISSUE THREAD

**Issue by whiteeat** [jlblancoc/suitesparse-metis-for-windows#85]
I finish the Instructions part, and there is no problem. But when it comes to Test program part, I try to generate Visual Studio projects for spqr using provided CMakeLists.txt, I have the following error:

>CMake Error at CMakeLists.txt:27 (include): 
include called with wrong number of arguments.  include() only takes one file.

I check the CMakeLists.txt, and can't find where the USE_SuiteSparse comes from. Then I just comment out some code like this:
```
LIST(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/../../cmakemodule/") # Add the directory where FindSuiteSparse.cmake module can be found.

set(SuiteSparse_USE_LAPACK_BLAS ON)
find_package(SuiteSparse QUIET NO_MODULE)  # 1st: Try to locate the *config.cmake file.
if(NOT SuiteSparse_FOUND)
        #set(SuiteSparse_VERBOSE ON)
        find_package(SuiteSparse REQUIRED) # 2nd: Use FindSuiteSparse.cmake module
        include_directories(${SuiteSparse_INCLUDE_DIRS})
else()
        # I comment out the following 2 lines of code using USE_SuiteSparse variable
        # message(STATUS "Find SuiteSparse : include(${USE_SuiteSparse})")
        # include(${USE_SuiteSparse})
endif()
```
Then, I can successfully generate the Visual Studio Solution and it seems to work. 

So, I don't know whether my fix is the correct way and whether there is a bug in the CMakeLists.txt?

**Comment by NeroBurner** [comment]
I think you are running in the problem I was thinking about here https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/80

try to remove the FindSuiteSparse.cmake file and set `-Dsuitesparse_DIR=/path/to/suitesparse-config.cmake` at your cmake-configuration step

**Comment by whiteeat** [comment]
> I think you are running in the problem I was thinking about here #80
> 
> try to remove the FindSuiteSparse.cmake file and set `-Dsuitesparse_DIR=/path/to/suitesparse-config.cmake` at your cmake-configuration step

@NeroBurner Yeah, I agree with you that we don't need FindSuiteSparse.cmake file if CMake can find the suitesparse-config.cmake. I use Windows and my CMake can find that suitesparse-config.cmake
if I provide a proper CMAKE_INSTALL_PREFIX. But there is still a problem on my side that in the latter part of the CMakelists, it tries to use USE_SuiteSparse variable, which is always empty. So is that the case also for you? Are you using Windows or Unix like operating systems?

**Comment by NeroBurner** [comment]
I use Linux, but I also did setup the CI for this repo, which includes MSVC builds on the Appveyor platform. When I want to find and use suitesparse I do the following

```
find_package(SuiteSparse CONFIG REQUIRED)
target_link_libraries(Foo PRIVATE ${SuiteSparse_LIBRARIES})
```

or I directly link the libraries I really need
```
	SuiteSparse::suitesparseconfig
	SuiteSparse::amd
	SuiteSparse::btf
	SuiteSparse::camd
	SuiteSparse::ccolamd
	SuiteSparse::colamd
	SuiteSparse::cholmod
	SuiteSparse::cxsparse
	SuiteSparse::klu
	SuiteSparse::ldl
	SuiteSparse::umfpack
	SuiteSparse::spqr
	SuiteSparse::metis
```

nothing else is required, no FindSuiteSparse.cmake, no USE_XXX variables, just the imported library targets (those also define the include directories, therefore you don't even need to use `target_include_directories()`)

**Comment by whiteeat** [comment]
@NeroBurner Thanks! Now I think I got it. But Probably I should keep this issue open until it is fixed in this repo officially?

**Comment by NeroBurner** [comment]
I'd say keep it open until the readme and examples are updated. You could even do a PR doing that if you'd like :)

**Comment by JeppeDruedahl** [comment]
When I follow the solution posted in this thread,  I cannot build the Visual Studio project as it cannot find the .h-files and the lapack .dll. I found some workarounds however. Details are given [here](https://github.com/JeppeDruedahl/SuiteSparsePythonWindows).

PS: Thanks for the developers of this repository! Amazing work.

**Comment by NeroBurner** [comment]
@JeppeDruedahl please open another issue with more detail and steps to reproduce the issue

**Comment by jlblancoc** [comment]
Docs updated, thanks @NeroBurner !! :+1:
