### ISSUE TITLE
Unresolved external symbol: METIS_NODEND and METIS_ComputeVertexSeparator

### ISSUE THREAD

**Issue by aschier** [jlblancoc/suitesparse-metis-for-windows#87]
I have problems with unresolved symbols similar to #7 when using suitesparse and ceres:

    1>libcholmod.lib(cholmod_metis.o.obj) : error LNK2019: unresolved external symbol METIS_NodeND referenced in function cholmod_metis
    1>libcholmod.lib(cholmod_metis.o.obj) : error LNK2019: unresolved external symbol METIS_ComputeVertexSeparator referenced in function cholmod_metis_bisector

Versions:
- Compiler: VS 2017
- Suitesparse-Metis: 1.4.0 (static)
- Ceres: 1.14.0 (static)
- OpenBLAS: 0.3.5 (shared)
- clapack: 3.2.1 (static)
- CMake: 3.14.0

A similar setup is working on a PC with VS 2015, but I think the problem is not related to the compiler itself. The libraries should be setup in a similar way as well, but I am not 100% sure about all CMake options (the old installation is a bit older than the new one). Any hints about possible causes of the error are welcome.

I need to look into a minimal example program, because I am not using suitesparse-metis directly.

**Comment by aschier** [comment]
Minimal example using ceres:

```
#include <ceres/ceres.h>

struct TestCostFunctor {
	template <typename T> bool operator()(T const *x0, T *residual) const {
		*residual = (T)0.0;
		return true;
	};
};

int main(){
	ceres::Solver::Options options;
	ceres::Problem problem;
	TestCostFunctor* cost_functor;
	auto *cost_function = new ceres::AutoDiffCostFunction<TestCostFunctor, 1, 1>(cost_functor);
	double x;
	problem.AddResidualBlock(cost_function, NULL, &x);

	ceres::Solver::Summary summary;
	ceres::Solve(options, &problem, &summary);
	return 0;
}
```

**Comment by NeroBurner** [comment]
thanks for the minimal example. A few more questions:

- Do you use cmake or something else to create the app?
- Where do you get your depencencies from? Do you use hunter to resolve dependencies or do you have them somewhere in your system?
- How do you resolve your dependencies? do you set system variables? or something else

**Comment by aschier** [comment]
I use cmake and I installed the dependencies myself on both systems. On the new system I have cmake 3.14.0 (latest), the one on the currently working system is still 3.11.1.

One issue with ceres and suitesparse on both systems was, that I need to add each library/include path for cholmod, ccolamd, amd, and colamd myself, because the autodetection did not work even when I set the suitesparse and suitesparseqr include/library paths before. I am not sure if this is related as it is the same on both systems as well, but as it has something to do with the library setup I wanted to mention it.

Is there something I can investigate where the symbols come from? As far as I understood the older issue, there was a patch, that renamed them some time ago and the old ones should not be referenced anymore by any header?

**Comment by NeroBurner** [comment]
a simple cmake project file building just the main executable (you mentioned earlier) and doing all the find_package stuff would be very helpful.

and then post the output of the following commands (with a clean build environment, and all your needed variables set)
```
cmake -S . -B _build -G "Visual Studio 15 2017 Win64"  -Dceres_DIR=path-to-the-ceres-config.cmake -Danother_variable=set-to-some-value
cmake --build _build
```

This will configure your cmake project to build with Visual Studio 2017 in 64bit mode. The second line actually builds your project

**Comment by aschier** [comment]
CMake:
```
cmake_minimum_required(VERSION 2.8.10)
project(problem)
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

find_package(Ceres REQUIRED SuiteSparse)
add_executable(test
        test.cpp
)
target_link_libraries(test
        ${CERES_LIBRARIES}
)
include_directories(test
        ${CERES_INCLUDE_DIRS}
)
```

Output:

```
$ cmake --build .
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  CMake does not need to re-run because C:/work/build/suitesparse-problem/CMakeFiles/generate.stamp is up-to-date.
  Building Custom Rule C:/work/code/suitesparse-problem/CMakeLists.txt
  CMake does not need to re-run because C:/work/build/suitesparse-problem/CMakeFiles/generate.stamp is up-to-date.
  test.cpp
c:\work\code\suitesparse-problem\test.cpp(14): warning C4700: uninitialized local variable 'cost_functor' used [C:\work\build\suitesparse-problem\test.vcxproj]
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\work\build\suitesparse-problem\test.vcxproj]
libcholmod.lib(cholmod_metis.o.obj) : error LNK2019: unresolved external symbol METIS_NodeND referenced in function cholmod_metis [C:\work\build\suitesparse-problem\test.vcxproj]
libcholmod.lib(cholmod_metis.o.obj) : error LNK2019: unresolved external symbol METIS_ComputeVertexSeparator referenced in function cholmod_metis_bisector [C:\work\build\suitesparse-problem\test.vcxproj]
C:\work\build\suitesparse-problem\Debug\test.exe : fatal error LNK1120: 2 unresolved externals [C:\work\build\suitesparse-problem\test.vcxproj]

```

**Comment by aschier** [comment]
Relevant CMakeCache.txt entries from my ceres build:

```
AMD_INCLUDE_DIR:PATH=C:/work/libs/suitesparse-metis-1.4.0/include/suitesparse
AMD_LIBRARY:FILEPATH=C:/work/libs/suitesparse-metis-1.4.0/lib/libamd.lib
CAMD_INCLUDE_DIR:PATH=C:/work/libs/suitesparse-metis-1.4.0/include/suitesparse
CAMD_LIBRARY:FILEPATH=C:/work/libs/suitesparse-metis-1.4.0/lib/libcamd.lib
CCOLAMD_INCLUDE_DIR:PATH=C:/work/libs/suitesparse-metis-1.4.0/include/suitesparse
CCOLAMD_LIBRARY:FILEPATH=C:/work/libs/suitesparse-metis-1.4.0/lib/libccolamd.lib
CHOLMOD_INCLUDE_DIR:PATH=C:/work/libs/suitesparse-metis-1.4.0/include/suitesparse
CHOLMOD_LIBRARY:FILEPATH=C:/work/libs/suitesparse-metis-1.4.0/lib/libcholmod.lib
COLAMD_INCLUDE_DIR:PATH=C:/work/libs/suitesparse-metis-1.4.0/include/suitesparse
COLAMD_LIBRARY:FILEPATH=C:/work/libs/suitesparse-metis-1.4.0/lib/libcolamd.lib
//Enable SuiteSparse.
SUITESPARSE:BOOL=ON
SUITESPARSEQR_INCLUDE_DIR:PATH=C:/work/libs/suitesparse-metis-1.4.0/include/suitesparse
SUITESPARSEQR_LIBRARY:FILEPATH=C:/work/libs/suitesparse-metis-1.4.0/lib/libspqr.lib
SUITESPARSE_CONFIG_INCLUDE_DIR:PATH=C:/work/libs/suitesparse-metis-1.4.0/include/suitesparse
SUITESPARSE_CONFIG_LIBRARY:FILEPATH=C:/work/libs/suitesparse-metis-1.4.0/lib/suitesparseconfig.lib
ceres_LIB_DEPENDS:STATIC=general;C:/work/libs/suitesparse-metis-1.4.0/lib/libspqr.lib;general;C:/work/libs/suitesparse-metis-1.4.0/lib/libcholmod.lib;general;C:/work/libs/suitesparse-metis-1.4.0/lib/libccolamd.lib;general;C:/work/libs/suitesparse-metis-1.4.0/lib/libcamd.lib;general;C:/work/libs/suitesparse-metis-1.4.0/lib/libcolamd.lib;general;C:/work/libs/suitesparse-metis-1.4.0/lib/libamd.lib;general;C:\work\libs\clapack-3.2.1\SRC\Release\lapack.lib;general;C:\work\libs\clapack-3.2.1\F2CLIBS\libf2c\Release\libf2c.lib;general;C:/work/libs/OpenBLAS-0.3.5/lib/openblas.lib;general;C:/work/libs/suitesparse-metis-1.4.0/lib/suitesparseconfig.lib;general;C:\work\libs\clapack-3.2.1\SRC\Release\lapack.lib;general;C:\work\libs\clapack-3.2.1\F2CLIBS\libf2c\Release\libf2c.lib;
//Details about finding SuiteSparse
FIND_PACKAGE_MESSAGE_DETAILS_SuiteSparse:INTERNAL=[TRUE][TRUE][TRUE][TRUE][TRUE][TRUE][TRUE][TRUE][5.1.0][v5.1.0()]
//ADVANCED property for variable: SUITESPARSEQR_INCLUDE_DIR
SUITESPARSEQR_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: SUITESPARSEQR_LIBRARY
SUITESPARSEQR_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: SUITESPARSE_CONFIG_INCLUDE_DIR
SUITESPARSE_CONFIG_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: SUITESPARSE_CONFIG_LIBRARY
SUITESPARSE_CONFIG_LIBRARY-ADVANCED:INTERNAL=1

```

**Comment by NeroBurner** [comment]
what happens if you remove `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)`?

Set `CeresDir` to the path where the file `CeresConfig.cmake` is installed to by ceres-solver

also try to set `SUITESPARSE_INCLUDE_DIR_HINTS` and `SUITESPARSE_LIBRARY_DIR_HINTS` as described in ceres findSuiteSparse module https://github.com/ceres-solver/ceres-solver/blob/1.14.x/cmake/FindSuiteSparse.cmake#L53

**Comment by aschier** [comment]
I set the HINTS settings, but still seem to need to configure the libraries (or setting one to "" overrides the autodetection, I did not start from scratch). I set ``Ceres_DIR`` anyway, so that ceres is found by my project.

I now added the HINTS settings to ceres, removed the ``CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`` and re-added the ``AMD_INCLUDE_DIR`` / ``AMD_LIBRARY`` and the example and my project are currently building without problems.

When I re-add ``CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS``, it is currently still building.

Full output:

```
CMake is re-running because C:/work/build/suitesparse-problem/CMakeFiles/generate.stamp is out-of-date.
  the file 'C:/work/code/suitesparse-problem/CMakeLists.txt'
  is newer than 'C:/work/build/suitesparse-problem/CMakeFiles/generate.stamp.depend'
  result='-1'
-- Found required Ceres dependency: Eigen version 3.3.7 in C:/work/libs/eigen-3.3.7
-- Found Ceres compiled with miniglog substitute for glog, beware this will likely cause problems if glog is later linked.
-- Ceres version 1.14.0 detected here: C:/work/libs/ceres-solver-1.14.0 was built with C++11. Ceres target will add C++11 flags to compile options for targets using it.
-- Found Ceres version: 1.14.0 installed in: C:/work/libs/ceres-solver-1.14.0 with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, SchurSpecializations, C++11, OpenMP, Multithreading]
-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/build/suitesparse-problem
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  test.vcxproj -> C:\work\build\suitesparse-problem\Debug\test.exe
```

Now I ask myself, where is the bug and will I be able to reproducible get it to run? I was installing it on a new PC and I use the opportunity to document what is needed to get everything to run, so closing this with "works for me" without knowing the issue and if it will break again is no good idea.

**Comment by NeroBurner** [comment]
make a completely clean build by removing the `_build` folder and then start again with the `cmake -S . -B _build <the rest of your variables>`. Please don't ever do an in-source-build by running `cmake --build .` inside the source folder. It's much better (and in the long run easier) to have an out-of-source build by specifying the build folder to be something other than the source folder. To have a completely fresh build you then only have to remove the `_build` folder (or however you named it) and run cmake again

**Comment by aschier** [comment]
I always do out of source builds and link against installed versions when possible (some projects like clawpack do not provide straightforward install-targets in their cmake files, then I use the build folder).
Currently we build most things statically for easier deployment, so things like missing symbols are only detected when finally building a binary.

I am now going to try to find the setting that caused the difference, but I wonder if there is somewhere more background on these symbols and if and where they should be defined?

**Comment by aschier** [comment]
I am now getting another message I never had before:

    -- Failed to find SuiteSparse - Could not find file: C:/work/libs/suitesparse-metis-1.4.0/include/SuiteSparse_config.h containing version information for >= v4 SuiteSparse installs, but SuiteSparse_config was found (only present in >= v4 installs).

**Comment by aschier** [comment]
I build suitesparse and ceres again from scratch, without and with the HINTS variables and it seems that the manual configuration of the suitesparse libraries in ceres is causing the problem. With a ceres build, that only uses the HINTS variables, I do not get the problem.

**Comment by aschier** [comment]
In addition it does not find libraries with a debug postfix, e.g., ``libamdd.lib``.

**Comment by NeroBurner** [comment]
upstream ceres does not use suitesparse-config.cmake to find suitesparse, it has a FindSuiteSparse.cmake module. You can try https://github.com/hunter-packages/ceres-solver/tree/hunter-1.14.0 for a version with patches to use suitesparse-config. It is intended to be used by [Hunter](https://github.com/ruslo/hunter) a C++ package manager like Conan, but written purely in CMake

**Comment by aschier** [comment]
I am still not sure where the symbols come from and why, but when every project has the correct cmake configuration as documented it works. So I close this bug.
If you want to investigate the symbols, reopen the bug.

Bottom line for others with the problem: Use the ``SUITESPARSE_INCLUDE_DIR_HINTS`` and ``SUITESPARSE_LIBRARY_DIR_HINTS`` settings when building ceres with suitesparse-metis-for-windows.

**Comment by chrisleong-nvg** [comment]
Hi, I am trying to test the example project cholmod and I got the same error as stated in this issue.
I've followed the README instructions but did not carry out step 3 as it was optional.
All CMake options were unchanged and left to default except for the following:
SuitSparse_DIR --> "suitsparse-metis-for-windows/build/install"

As for the example project I am using VisualStudios 2017 x64 debug mode
The .sln was generated by running CMake 3.13.0 after copying FindSuiteSparse.cmake to the example-projects/cholmod. It did not populate the property pages for C++/General/Includes and I had to manually add "suitsparse-metis-for-windows/build/install" to it.

I believe I may be missing the .lib files for metis?

**Comment by NeroBurner** [comment]
don't use FindSuiteSparse.cmake. we desperately need to cleanup the documentation for it
https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/80

**Comment by chrisleong-nvg** [comment]
I've removed the FindSuitSparse.cmake from the `example-projects/cholmod` and deleted the `example-projects/cholmod` directory and modified the cmake entry `SuitSparse_DIR=suitesparse-metis-for-windows/build/SuiteSparse` but now I am getting an error in CMake:

> CMake Error at CMakeLists.txt:27 (include):
>   include called with wrong number of arguments.  include() only takes one
>   file.


I think it may be still pointing to the old cmake file I deleted but im not sure?
Inside `suitesparse-metis-for-windows/build/SuiteSparse` I do see the `suitesparse-config.cmake` you mentioned in #80 so I'm not sure what else to do.

**Comment by chrisleong-nvg** [comment]
I reverted the CMake Entry `SuiteSparse_DIR=suitesparse-metis-for-windows/build/SuiteSparse` to `SuiteSparse_DIR-NOTFOUND` and ran CMake for the example project again and got this error:

> CMake Error at D:/Workspace/SuiteSparse/suitesparse-metis-for-windows/cmakemodule/FindSuiteSparse.cmake:468 (MESSAGE):
>   SuiteSparse required but some headers or libs not found.
> Call Stack (most recent call first):
>   CMakeLists.txt:23 (find_package)

My assumption is right and it is still trying to call `FindSuiteSparse.cmake` 

After that I overwrote the CMake entry: `SuiteSparse_SUITESPARSECONFIG_DIR` to point to `suitesparse-metis-for-windows/build/SuiteSparse` but it still complains about FindSuitSparse.cmake not finding headers/.lib files.

**Comment by chrisleong-nvg** [comment]
I deleted the repo and re-did all the steps in README.md (minus copying `FindSuiteSparse.cmake`) but I am unable to reach the same state.
Now when I open CMake to build `example-projects/cholmod` I no longer see the SuiteSparse entry group.

**Comment by chrisleong-nvg** [comment]
I resolved the errors.
Here are my steps:

- Delete repo and clone again.
- Follow all steps but the optional portions in step3
- Comment out the 2 lines in the file: `example-projects/cholmod/CMakeLists.txt`
`        #message(STATUS "Find SuiteSparse : include(${USE_SuiteSparse})")
        #include(${USE_SuiteSparse})`
- Run CMake GUI on it

Program now compiles and runs.

**Comment by NeroBurner** [comment]
If you've got the time and motivation: could you send a pull request with the changes you've mentioned? That would be awesome

**Comment by NeroBurner** [comment]
@chrisleong-nvg we updated the generated `suitesparse-config.cmake` could you test again if it solves your issue?
