### ISSUE TITLE
Noob question for building the code

### ISSUE THREAD

**Issue by petrasvestartas** [jlblancoc/suitesparse-metis-for-windows#90]
Hi,

I am new to C++ and new to CMAKE, but I really need to build this library for my project.

I do not know if I did it correctly.
I downloaded the github folder, installed cmake, opened cmake, selected the directory of unrarred folder and pressed build.
I did not do anything else. The build is succeeded.

I attach the screenshots of my steps. Could you check if this correct?

![2019-04-27 (2)](https://user-images.githubusercontent.com/18013985/56853592-beb00a00-6932-11e9-8847-335618a84724.png)
![2019-04-27 (1)](https://user-images.githubusercontent.com/18013985/56853593-beb00a00-6932-11e9-865b-7ffd48d864b1.png)
![2019-04-27](https://user-images.githubusercontent.com/18013985/56853594-beb00a00-6932-11e9-96ad-228e8a4f346f.png)

**Comment by jlblancoc** [comment]
Yes, it was all correct.
