### ISSUE TITLE
does the suitesparse project  support cross compile and build for android running?

### ISSUE THREAD

**Issue by lligen** [jlblancoc/suitesparse-metis-for-windows#91]
hello,

does the suitesparse project  support cross compile and build for android running?

**Comment by NeroBurner** [comment]
I haven't tried compiling for android, but I think there is nothing fundamentally stopping you. I have successfully compiled SuiteSparse for armhf and arm64

Give it a go and report back. I'd love to know

On August 22, 2019 9:41:51 AM GMT+02:00, lligen <notifications@github.com> wrote:
>hello,
>
>does the suitesparse project  support cross compile and build for
>android running?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/91

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lligen** [comment]
hi, @NeroBurner 
i have successfully compiled SuiteSparse for android armv7/aarch64 static libs with  opencv's 
[android.toolchain.cmake](https://github.com/opencv/opencv/blob/19a4b5137149e43fa85bef16707c40b535d195b4/platforms/android/android.toolchain.cmake)

by the way, one should pre-build openblas [How-to-build-OpenBLAS-for-Android](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android) before compile SuiteSparse.

thanks for your work.

**Comment by jlblancoc** [comment]
Great, thanks for reporting back!! :+1:

**Comment by lligen** [comment]
hi, 
i have another question, 
can we compiled suitesparse with GPU-supported on android?

**Comment by NeroBurner** [comment]
if you get CUDA for Android working, then I think yes. But I have no experience with CUDA
https://docs.nvidia.com/gameworks/content/technologies/mobile/cuda_android_main.htm

**Comment by TennisAndy** [comment]
@lligen Hi, I have pre-built [openblas How-to-build-OpenBLAS-for-Android ](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android) and get the libopenblas_armv7p-r0.3.9.dev.so file, but still don't know how to cross compile SuiteSparse, can you help me?
