### ISSUE TITLE
Could not find SuiteSparseConfig.cmake

### ISSUE THREAD

**Issue by zhangzheng0317** [jlblancoc/suitesparse-metis-for-windows#93]
Sorry,  i could't find SuiteSparseConfig.cmake in my install directory but find suitesparse-config.cmake in install\lib\cmake\suitesparse-5.4.0 directory ,is right?

**Comment by NeroBurner** [comment]
yes, that's intended

set `-DSuiteSparse_DIR="/path/to/install/lib/cmake/suitesparse-5.4.0"` when configuring your other project using suitesparse

**Comment by zhangzheng0317** [comment]
> yes, that's intended
> 
> set `-DSuiteSparse_DIR="/path/to/install/lib/cmake/suitesparse-5.4.0"` when configuring your other project using suitesparse
thank you!

**Comment by zhangzheng0317** [comment]
solved
