### ISSUE TITLE
 FindSuiteSparse.cmake dead link

### ISSUE THREAD

**Issue by shrddr** [jlblancoc/suitesparse-metis-for-windows#94]
readme.md

> 3. Integration in your code (unique code for Windows/Linux)
> Copy this FindSuiteSparse.cmake file. 

404

**Comment by NeroBurner** [comment]
the documentation is a bit out of date :sweat_smile: 

To build with Visual Studio 2017 the following commands should work (when LAPACK and BLAS are supplied)
```
cmake -S . -B _build -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=%cd%\_install
cmake --build _build --config Release --target install
```

in another config either set the `CMAKE_PREFIX_PATH` or more specifically the `SuiteSparse_DIR` variable

**Comment by G86char** [comment]
@NeroBurner 

About MinGW compiler. I noticed that the MinGW doesn't support this "-Wl" option.

When my project was compiled by GCC, it used this "-Wl, --whole-archive" option to avoid some errors like "undefined reference to some functions".  However, the MinGW-W64 under Ubuntu seems not to support such options.  

May I have some suggestions about how to compile a project without the "-Wl" options? Thanks in advance.

**Comment by NeroBurner** [comment]
@G86char please open another issue, or reopen your previous one, and then ping me over there

**Comment by G86char** [comment]
@NeroBurner

About MinGW compiler. I noticed that the MinGW doesn't support this "-Wl" option.

When my project was compiled by GCC, it used this "-Wl, --whole-archive" option to avoid some errors like "undefined reference to some functions". However, the MinGW-W64 under Ubuntu seems not to support such options.

May I have some suggestions about how to compile a project without the "-Wl" options? Thanks in advance.

**Comment by NeroBurner** [comment]
Please provide some more info on what you want to do and your project structure. Maybe provide a minimal example (here or create a github project)

As a guess in the dark maybe the -fPIC flag (position independent code) may be what you are looking for
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
