### ISSUE TITLE
How to compile suitesparse for Windows on Linux with mingw ?

### ISSUE THREAD

**Issue by G86char** [jlblancoc/suitesparse-metis-for-windows#95]
I am working a cross compiling project on Linux for Windows.  My project needs this suitesparse package.   I have cross compiled BLAS and LAPACK through MXE.  However, I couldn't use the same progress to cross compile "suitesparse-metis-for-windows".

If I want to cross compile suitesparse through mingw, is there any tutorial or comment?   Thanks.

**Comment by NeroBurner** [comment]
I've compiled with mingw-w64 under ubuntu, fedora or arch. You need the mingw compiler and if not installed by default also the mingw-w64-gfortran compiler

After installation compile with cmake and add -DCMAKE_TOOLCHAIN_FILE=ci/toolchains/linux-mingw-w64-cxx17.cmake

https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/ci/toolchains/linux-mingw-w64-cxx17.cmake

For cross compillation I like cpp-pm/hunter as package manager, as it compiles the dependencies from source

**Comment by G86char** [comment]
@NeroBurner  Thanks so much for your help, and I do appreciate it.  

I followd your method and cross compiled suitesparse package successfully, and it works well with my project.   Thanks!

**Comment by G86char** [comment]
@NeroBurner

About MinGW compiler. I noticed that the MinGW doesn't support this "-Wl" option.

When my project was compiled by GCC, it used this "-Wl, --whole-archive" option to avoid some errors like "undefined reference to some functions". However, the MinGW-W64 under Ubuntu seems not to support such options.

May I have some suggestions about how to compile a project without the "-Wl" options? Thanks in advance.

**Comment by NeroBurner** [comment]
Please provide some more info on what you want to do and your project structure. Maybe provide a minimal example (here or create a github project)

As a guess in the dark maybe the -fPIC flag (position independent code) may be what you are looking for

**Comment by G86char** [comment]
@NeroBurner  Thanks for your quick reply.  And I do appreciate for your help. 

 I spent two days to figure out that actually the MinGW compiler support "-Wl" option.   I tested this "-Wl,--whole-archive" option, and it worked with MinGW.

I copied parts of CMakeOutput.Log and CMakeError.Log as following:

> Run Build Command:"/usr/bin/make" "cmTC_48bea/fast"
/usr/bin/make -f CMakeFiles/cmTC_48bea.dir/build.make CMakeFiles/cmTC_48bea.dir/build
make[1]: Entering directory '/home/yunic/OPLWIN/polymer-simulators86/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_48bea.dir/DummyCXXFile.cxx.obj
/usr/bin/x86_64-w64-mingw32-g++     -std=c++14 -pipe -Wall -Wextra -Wshadow -fopenmp -pthread   -o CMakeFiles/cmTC_48bea.dir/DummyCXXFile.cxx.obj -c /usr/share/cmake-3.5/Modules/DummyCXXFile.cxx
Linking CXX executable cmTC_48bea.exe
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_48bea.dir/link.txt --verbose=1
/usr/bin/cmake -E remove -f CMakeFiles/cmTC_48bea.dir/objects.a
/usr/bin/x86_64-w64-mingw32-ar cr CMakeFiles/cmTC_48bea.dir/objects.a @CMakeFiles/cmTC_48bea.dir/objects1.rsp
/usr/bin/x86_64-w64-mingw32-g++  -std=c++14 -pipe -Wall -Wextra -Wshadow -fopenmp -pthread    -Wl,--whole-archive CMakeFiles/cmTC_48bea.dir/objects.a -Wl,--no-whole-archive  -o cmTC_48bea.exe -Wl,--out-implib,libcmTC_48bea.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/cmTC_48bea.dir/linklibs.rsp
make[1]: Leaving directory '/home/yunic/OPLWIN/polymer-simulators86/build/CMakeFiles/CMakeTmp'


The CMakeError.Log :

> Linking CXX executable cmTC_55b5a.exe
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_55b5a.dir/link.txt --verbose=1
/usr/bin/cmake -E remove -f CMakeFiles/cmTC_55b5a.dir/objects.a
/usr/bin/x86_64-w64-mingw32-ar cr CMakeFiles/cmTC_55b5a.dir/objects.a @CMakeFiles/cmTC_55b5a.dir/objects1.rsp
/usr/bin/x86_64-w64-mingw32-g++  -std=c++14 -pipe -Wall -Wextra -Wshadow -fopenmp -pthread -DHAVE_DYNAMIC_BOOST_TEST    -Wl,--whole-archive CMakeFiles/cmTC_55b5a.dir/objects.a -Wl,--no-whole-archive  -o cmTC_55b5a.exe -Wl,--out-implib,libcmTC_55b5a.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/cmTC_55b5a.dir/linklibs.rsp
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text+0x7d): undefined reference to `__imp__ZN5boost9unit_test9framework17master_test_suiteEv'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text+0xe6): undefined reference to `__imp__ZN5boost9unit_test14unit_test_mainEPFbvEiPPc'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text+0x199): undefined reference to `__imp__ZN5boost9unit_test15unit_test_log_t14set_checkpointENS0_13basic_cstringIKcEEyS4_'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text+0x25b): undefined reference to `__imp__ZN5boost10test_tools9tt_detail10check_implERKNS0_16predicate_resultERKNS_9unit_test12lazy_ostreamENS5_13basic_cstringIKcEEyNS1_10tool_levelENS1_10check_typeEyz'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text+0x398): undefined reference to `__imp__ZN5boost9unit_test9ut_detail24auto_test_unit_registrarC1EPNS0_9test_caseEm'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text$_ZN5boost9unit_test13test_observerD2Ev[_ZN5boost9unit_test13test_observerD2Ev]+0xf): undefined reference to `__imp__ZTVN5boost9unit_test13test_observerE'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text$_ZN5boost9unit_test13test_observerD1Ev[_ZN5boost9unit_test13test_observerD1Ev]+0xf): undefined reference to `__imp__ZTVN5boost9unit_test13test_observerE'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text$_ZN5boost9unit_test13test_observerC2Ev[_ZN5boost9unit_test13test_observerC2Ev]+0xb): undefined reference to `__imp__ZTVN5boost9unit_test13test_observerE'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text$_ZN5boost9unit_test15unit_test_log_tC1Ev[_ZN5boost9unit_test15unit_test_log_tC1Ev]+0x24): undefined reference to `__imp__ZTVN5boost9unit_test15unit_test_log_tE'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text$_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE[_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE]+0x3e): undefined reference to `__imp__ZN5boost9unit_test9ut_detail24normalize_test_case_nameB5cxx11ENS0_13basic_cstringIKcEE'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text$_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE[_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE]+0x82): undefined reference to `__imp__ZN5boost9unit_test9test_caseC1ENS0_13basic_cstringIKcEERKNS0_9callback0INS0_9ut_detail6unusedEEE'
CMakeFiles/cmTC_55b5a.dir/objects.a(src.cxx.obj):src.cxx:(.text$_ZN5boost9unit_test15unit_test_log_tD1Ev[_ZN5boost9unit_test15unit_test_log_tD1Ev]+0xf): undefined reference to `__imp__ZTVN5boost9unit_test15unit_test_log_tE'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_55b5a.dir/build.make:101: recipe for target 'cmTC_55b5a.exe' failed
make[1]: *** [cmTC_55b5a.exe] Error 1


What I have noticed is that "HAVE_DYNAMIC_BOOST_TEST" option.  It can work with Linux gcc, but cannot pass test with MinGW.   I doubt maybe this is the problem,and I am working on this now.  

Could you please give me some suggestions or hints please?  I have no clue right now.  Thanks in advance.

**Comment by NeroBurner** [comment]
It looks to me, that you are using boost.test, but forgot to link to the dynamic boost.test library. I think there is a header only variant of boost test, then you don't need the dynamic library.
see https://www.boost.org/doc/libs/1_72_0/libs/test/doc/html/boost_test/usage_variants.html#boost_test.usage_variants.single_header

Alternatively I can recommend Catch2 as testing framework. It is currently my favorite testing framework and can be used by including a single header file https://github.com/catchorg/Catch2/releases (download just `catch.hpp`)

**Comment by G86char** [comment]
@NeroBurner   Thanks so much for your quickly reply and suggestions.  

I had re-compiled the project again and found out that maybe this "HAVE_DYNAMIC_BOOST_TEST" option was not the reason for my project failure. 

I have compiled this project successfully with GCC on Ubuntu.  Currently, I am working on cross compiling it with MinGW on Ubuntu.   Then I met the following errors:

> [ 23%] Linking CXX executable bin/ebos.exe
/usr/bin/cmake -E cmake_link_script CMakeFiles/ebos.dir/link.txt --verbose=1
/usr/bin/cmake -E remove -f CMakeFiles/ebos.dir/objects.a
/usr/bin/x86_64-w64-mingw32-ar cr CMakeFiles/ebos.dir/objects.a @CMakeFiles/ebos.dir/objects1.rsp
/usr/bin/x86_64-w64-mingw32-g++  -std=c++14 -pipe -Wall -Wextra -Wshadow -fopenmp -pthread -O3 -mtune=native  CMakeFiles/ebos.dir/objects.a -u Exception  -o bin/ebos.exe  @CMakeFiles/ebos.dir/linklibs.rsp
CMakeFiles/ebos.dir/objects.a(ebos_blackoil.cc.obj):ebos_blackoil.cc:(.text+0x393e): undefined reference to `Dune::Exception::Exception()'
CMakeFiles/ebos.dir/objects.a(ebos_blackoil.cc.obj):ebos_blackoil.cc:(.text+0x3a3f): undefined reference to `Dune::Exception::message(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/ebos.dir/objects.a(ebos_blackoil.cc.obj):ebos_blackoil.cc:(.text+0x55db): undefined reference to `Dune::ParameterTree::hasKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/ebos.dir/objects.a(ebos_blackoil.cc.obj):ebos_blackoil.cc:(.text+0x580e): undefined reference to `Dune::ParameterTree::hasKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/ebos.dir/objects.a(ebos_blackoil.cc.obj):ebos_blackoil.cc:(.text+0x6c5c): undefined reference to `Dune::ParameterTree::hasKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'


During linking phase, there are several "undefined reference" errors.  And this "Dune" is an external library.  At first, I thought the reason was this "Wl,-whole-archive" didn't work.  However, my test proved that MinGW do support this option and it worked.  

It seems to me that this is problem of linking to external libraries.  But I am not sure about it.  May I have some suggestions or comments?  Thanks in advance.

**Comment by NeroBurner** [comment]
I don't know if `-mtune=native` is a good idea for cross compilation, I'd try to remove this option

somewhere you have to tell the compiler to link against the dune library and it needs to be compatible with the build target you are building (windows vs linux) otherwise it cant link together

see documentation for `target_link_libraries()` and `find_package()`

**Comment by NeroBurner** [comment]
@G86char any updates on this?

**Comment by NeroBurner** [comment]
@jlblancoc please close this Issue due to inactivity
