### ISSUE TITLE
SuiteSparse with CUDA 9.2 cannot pass the test

### ISSUE THREAD

**Issue by YingmoWang** [jlblancoc/suitesparse-metis-for-windows#99]
SuiteSparse with CUDA 9.2 （Also with MKL）has been compiled Successfully but cannot pass the CUDA test.The test link is here: https://gist.github.com/andr3wmac/78d294844484cb48342f88ef03e2776a

The building environment is Win10 and Visual Studio 2017. x64 platform.

When i run the solver, it will take all my PC's memory (About 8 GB)， and throw an Error finally.
Exception Codes: 0x0000000000000000,

Anyone has experience about the SuiteSparse with CUDA?

Thanks for your kindly suggestions and help!

**Comment by NeroBurner** [comment]
@YingmoWang Did you find a solution to your problem?

**Comment by YingmoWang** [comment]
> @YingmoWang Did you find a solution to your problem?

Hi, I find out that the nvblas.conf cause this, finally. I had something wrong with NVBLAS_CPU_BLAS_LIB. 

However, I find that the SuiteSparse using GPU is slower than CPU.

This is the log of the CUDA Test when using GPU
`Loading matrix..
CHOLMOD sparse:  A:  18000-by-18000, nz 3457658, upper.  OK
CHOLMOD error: out of memory. file: C:\Users\MLoong\Desktop\suitesparse-metis-for-windows-master\SuiteSparse\CHOLMOD\Include\../Core/cholmod_memory.c line: 146
Cholesky Took: 3.253(s).

CHOLMOD GPU/CPU statistics:
SYRK  CPU calls            0 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
GEMM  CPU calls            0 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
POTRF CPU calls            0 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
TRSM  CPU calls            0 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
time in the BLAS: CPU   0.0000e+00 GPU   0.0000e+00 total:   0.0000e+00
assembly time   0.0000e+00    0.0000e+00`


This is the log of the CUDA Test when using CPU
`Loading matrix..
CHOLMOD sparse:  A:  18000-by-18000, nz 3457658, upper.  OK
[NVBLAS] NVBLAS_CONFIG_FILE environment variable is set to 'D:\nvblas.conf'
Cholesky Took: 5.312(s).

CHOLMOD GPU/CPU statistics:
SYRK  CPU calls          781 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
GEMM  CPU calls          618 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
POTRF CPU calls          164 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
TRSM  CPU calls          163 time   0.0000e+00
      GPU calls            0 time   0.0000e+00
time in the BLAS: CPU   0.0000e+00 GPU   0.0000e+00 total:   0.0000e+00
assembly time   0.0000e+00    0.0000e+00`
